package com.dante.model.apiInfo;

import java.util.List;

import com.dante.model.base.BaseRecord;

public class ApiInfo extends BaseRecord{
    /**
	 * 序列号
	 */
	private static final long serialVersionUID = -9055354659337834979L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DANTE_API_INFO.API_INFO_ID
     *
     * @mbg.generated
     */
    private String apiInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DANTE_API_INFO.API_INFO_NAME
     *
     * @mbg.generated
     */
    private String apiInfoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DANTE_API_INFO.API_INFO_DESCRIPTION
     *
     * @mbg.generated
     */
    private String apiInfoDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DANTE_API_INFO.API_INFO_URL
     *
     * @mbg.generated
     */
    private String apiInfoUrl;
    
    /**
     * 入参列表
     */
    private List<ApiColumn> paramInList;
    
    /**
     * 出参列表
     */
    private List<ApiColumn> paramOutList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DANTE_API_INFO.API_INFO_ID
     *
     * @return the value of DANTE_API_INFO.API_INFO_ID
     *
     * @mbg.generated
     */
    public String getApiInfoId() {
        return apiInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DANTE_API_INFO.API_INFO_ID
     *
     * @param apiInfoId the value for DANTE_API_INFO.API_INFO_ID
     *
     * @mbg.generated
     */
    public void setApiInfoId(String apiInfoId) {
        this.apiInfoId = apiInfoId == null ? null : apiInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DANTE_API_INFO.API_INFO_NAME
     *
     * @return the value of DANTE_API_INFO.API_INFO_NAME
     *
     * @mbg.generated
     */
    public String getApiInfoName() {
        return apiInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DANTE_API_INFO.API_INFO_NAME
     *
     * @param apiInfoName the value for DANTE_API_INFO.API_INFO_NAME
     *
     * @mbg.generated
     */
    public void setApiInfoName(String apiInfoName) {
        this.apiInfoName = apiInfoName == null ? null : apiInfoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DANTE_API_INFO.API_INFO_DESCRIPTION
     *
     * @return the value of DANTE_API_INFO.API_INFO_DESCRIPTION
     *
     * @mbg.generated
     */
    public String getApiInfoDescription() {
        return apiInfoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DANTE_API_INFO.API_INFO_DESCRIPTION
     *
     * @param apiInfoDescription the value for DANTE_API_INFO.API_INFO_DESCRIPTION
     *
     * @mbg.generated
     */
    public void setApiInfoDescription(String apiInfoDescription) {
        this.apiInfoDescription = apiInfoDescription == null ? null : apiInfoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DANTE_API_INFO.API_INFO_URL
     *
     * @return the value of DANTE_API_INFO.API_INFO_URL
     *
     * @mbg.generated
     */
    public String getApiInfoUrl() {
        return apiInfoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DANTE_API_INFO.API_INFO_URL
     *
     * @param apiInfoUrl the value for DANTE_API_INFO.API_INFO_URL
     *
     * @mbg.generated
     */
    public void setApiInfoUrl(String apiInfoUrl) {
        this.apiInfoUrl = apiInfoUrl == null ? null : apiInfoUrl.trim();
    }

	public List<ApiColumn> getParamInList() {
		return paramInList;
	}

	public void setParamInList(List<ApiColumn> paramInList) {
		this.paramInList = paramInList;
	}

	public List<ApiColumn> getParamOutList() {
		return paramOutList;
	}

	public void setParamOutList(List<ApiColumn> paramOutList) {
		this.paramOutList = paramOutList;
	}
    
}