package com.dante.model.apiInfo;

import com.dante.model.base.BaseRecord;

public class ColumnInfo extends BaseRecord{
    /**
	 * 序列号
	 */
	private static final long serialVersionUID = -2762520793637523264L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DANTE_COLUMN_INFO.COLUMN_INFO_ID
     *
     * @mbg.generated
     */
    private String columnInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DANTE_COLUMN_INFO.COLUMN_INFO_NAME
     *
     * @mbg.generated
     */
    private String columnInfoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DANTE_COLUMN_INFO.COLUMN_INFO_TYPE
     *
     * @mbg.generated
     */
    private String columnInfoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DANTE_COLUMN_INFO.COLUMN_INFO_PARENT
     *
     * @mbg.generated
     */
    private String columnInfoParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DANTE_COLUMN_INFO.COLUMN_INFO_ID
     *
     * @return the value of DANTE_COLUMN_INFO.COLUMN_INFO_ID
     *
     * @mbg.generated
     */
    public String getColumnInfoId() {
        return columnInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DANTE_COLUMN_INFO.COLUMN_INFO_ID
     *
     * @param columnInfoId the value for DANTE_COLUMN_INFO.COLUMN_INFO_ID
     *
     * @mbg.generated
     */
    public void setColumnInfoId(String columnInfoId) {
        this.columnInfoId = columnInfoId == null ? null : columnInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DANTE_COLUMN_INFO.COLUMN_INFO_NAME
     *
     * @return the value of DANTE_COLUMN_INFO.COLUMN_INFO_NAME
     *
     * @mbg.generated
     */
    public String getColumnInfoName() {
        return columnInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DANTE_COLUMN_INFO.COLUMN_INFO_NAME
     *
     * @param columnInfoName the value for DANTE_COLUMN_INFO.COLUMN_INFO_NAME
     *
     * @mbg.generated
     */
    public void setColumnInfoName(String columnInfoName) {
        this.columnInfoName = columnInfoName == null ? null : columnInfoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DANTE_COLUMN_INFO.COLUMN_INFO_TYPE
     *
     * @return the value of DANTE_COLUMN_INFO.COLUMN_INFO_TYPE
     *
     * @mbg.generated
     */
    public String getColumnInfoType() {
        return columnInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DANTE_COLUMN_INFO.COLUMN_INFO_TYPE
     *
     * @param columnInfoType the value for DANTE_COLUMN_INFO.COLUMN_INFO_TYPE
     *
     * @mbg.generated
     */
    public void setColumnInfoType(String columnInfoType) {
        this.columnInfoType = columnInfoType == null ? null : columnInfoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DANTE_COLUMN_INFO.COLUMN_INFO_PARENT
     *
     * @return the value of DANTE_COLUMN_INFO.COLUMN_INFO_PARENT
     *
     * @mbg.generated
     */
    public String getColumnInfoParent() {
        return columnInfoParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DANTE_COLUMN_INFO.COLUMN_INFO_PARENT
     *
     * @param columnInfoParent the value for DANTE_COLUMN_INFO.COLUMN_INFO_PARENT
     *
     * @mbg.generated
     */
    public void setColumnInfoParent(String columnInfoParent) {
        this.columnInfoParent = columnInfoParent == null ? null : columnInfoParent.trim();
    }

  }